# Auto-generated by scripts/harden_build_attest.py; do not edit manually.
# Generated at 2025-12-09T12:29:08.091351+00:00
EXPECTED_SELF_SHA256 = {
    "attest.cpython-310-darwin.so": "b8f71afeffd9e7e0fd2cc31ddee2929eadf16fed4698a8102ff12c27312d0420",
    "attest.cpython-310-x86_64-linux-gnu.so": "f779f963991ac267e9e5738929c3a5c96bb2da04f4d407699908ba391c4824c6",
}
